### ISSUE TITLE
add support ffmpeg 6.1

### ISSUE THREAD

**Issue by peacess** [CCExtractor/rusty_ffmpeg#100]

**Comment by ldm0** [comment]
I've locally tested ffmpeg 6.1 with rusty_ffmpeg yesterday, and everything seems fine.

**Comment by whamer100** [comment]
im having issues getting 6.1 to be used, im getting this error:
```
error[E0587]: type has conflicting packed and align representation hints
 --> C:\Projects\Rust\rs_gtproj\target\debug\build\rusty_ffmpeg-1acc2c7ce02b39bd\out/binding.rs:3:81514
  |
3 | ... # [repr (C , packed (8))] # [repr (align (8))] # [derive (Copy , Clone)] pub union __mingw_ldbl_type_t { pub x : u128 , pub lh : __mingw_ldbl_type_t__bindgen_ty_1 , } # [repr (C... 
  |         
 ```
any suggestions? im using cargo-vcpkg on windows with the line `x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md", dependencies = ["ffmpeg"] }` for the `package.metadata.vcpkg.target` bit in the toml

**Comment by ldm0** [comment]
@whamer100 Nope, you didn't do anything wrong. It seems to be a bindgen bug: https://github.com/rust-lang/rust-bindgen/issues/2159.

**Comment by ldm0** [comment]
I am going to reproduce it on my windows machine and create a patch later.

**Comment by whamer100** [comment]
> @whamer100 Nope, you didn't do anything wrong. It seems to be a bindgen bug: [rust-lang/rust-bindgen#2159](https://github.com/rust-lang/rust-bindgen/issues/2159).

good to know, and thank you
