### ISSUE TITLE
Better enum type name

### ISSUE THREAD

**Issue by ldm0** [CCExtractor/rusty_ffmpeg#38]
Current we got enum like this:
```rust
pub const AVMediaType_AVMEDIA_TYPE_NB: AVMediaType = 5;
```
Which is not good to use. And the rust-bindgen provides us several options: <https://docs.rs/bindgen/0.55.1/bindgen/struct.Builder.html>

However they all not suitable for out situation. I want the generated enum can be directly `use`d(`rustified_enum` creates const in impl, which cannot be `use`d just like the bitflags crate does), and is able to do calculation(which makes `newtype_enum` not suitable, it construct a new_type containing a integer), and extendable(some consts cnanot be directly generated with bindgen, which need to be add by hand, but generate const value in a specific module makes adding them not possible), The `bitfield_enum` is better but each enum only occupies a bit, which makes the maximum number of each enum is limited.

The last option is trimming the prefix of each enum, which is suitable since FFmpeg's enum name never overlaps. So it's blocked on https://github.com/rust-lang/rust-bindgen/issues/777

**Comment by ldm0** [comment]
The problem is the callback receives unprefixed identifier, like the AVMEDIA_TYPE_VIDEO for AVMediaType_AVMEDIA_TYPE_VIDEO, which makes it impossible to trim out the AVMediaType. So depending on the https://github.com/rust-lang/rust-bindgen/issues/777 is impossible.

**Comment by Zerowalker** [comment]
is the idea to make `enum` out of the types, but it's hard to determine what actually is within said `enum`?

**Comment by jgcodes2020** [comment]
> Current we got enum like this:
> 
> ```rust
> pub const AVMediaType_AVMEDIA_TYPE_NB: AVMediaType = 5;
> ```
> 
> Which is not good to use. And the rust-bindgen provides us several options: https://docs.rs/bindgen/0.55.1/bindgen/struct.Builder.html
> 
> However they all not suitable for out situation. I want the generated enum can be directly `use`d (`rustified_enum` creates const in impl, which cannot be `use`d just like the bitflags crate does), and ***is able to do calculation*** (which makes `newtype_enum` not suitable, it construct a new_type containing a integer), and extendable(some consts cnanot be directly generated with bindgen, which need to be add by hand, but generate const value in a specific module makes adding them not possible), The `bitfield_enum` is better but each enum only occupies a bit, which makes the maximum number of each enum is limited.
> 
> The last option is trimming the prefix of each enum, which is suitable since FFmpeg's enum name never overlaps. So it's blocked on [rust-lang/rust-bindgen#777](https://github.com/rust-lang/rust-bindgen/issues/777)

What exactly is doing math on the constants useful for? I see no other issues with `newtype_enum` if not for that.

**Comment by ldm0** [comment]
> What exactly is doing math on the constants useful for?

Enums defined as bitflags are widely used in FFmpeg, [e.g.](https://github.com/FFmpeg/FFmpeg/blob/8e23ebe6f971ec4177be73b453960d83c264b7b5/libavutil/vulkan_functions.h#L29), you need to do math on them for sure.

> you could just as well inline the extra enum constants.

Yeah, but defining extra enums has several drawbacks:

1. It's confusing that there are two same looking definitions, users won't get it clear and usage will messed up by the two variants.
2. Auto-generated functions accept and emit enum as i32. Users need to cast the enum back and forth which looks awkward.

I still think it would be better to let bindgen define the enum. Until it is capable, we should use i32 instead of our own defined enums.
