### ISSUE TITLE
AVDRMFrameDescriptor is not exported

### ISSUE THREAD

**Issue by FallingSnow** [CCExtractor/rusty_ffmpeg#58]
How do I get access to AVDRMFrameDescriptor?

https://github.com/FFmpeg/FFmpeg/blob/870bfe16a12bf09dca3a4ae27ef6f81a2de80c40/libavutil/hwcontext_drm.h#L133

**Comment by ldm0** [comment]
You can simply fork the `rusty_ffmpeg` and add "libavutil/hwcontext_drm.h" to this array in build script: <https://github.com/CCExtractor/rusty_ffmpeg/blob/01f78269ac24469aa9dbfb8a1bfe5c0879f7df87/build.rs#L20>

Then you can access it.

**Comment by FallingSnow** [comment]
Ah! Thank you!

Just curious, is there a reason you don't include it? It it because you only select the most commonly used headers?

**Comment by ldm0** [comment]
> Ah! Thank you!
> 
> Just curious, is there a reason you don't include it? It it because you only select the most commonly used headers?

Yes.
