### ISSUE TITLE
Is AV_PIX_FMT_NV12 missing?

### ISSUE THREAD

**Issue by Zerowalker** [CCExtractor/rusty_ffmpeg#88]
As title says, i noticed i can't find it, but it should exist: https://github.com/FFmpeg/FFmpeg/blob/ed83a3a5bddf4c209157dc9f041eda0721b4c3e0/libavutil/pixfmt.h

**Comment by ldm0** [comment]
Nope, it exists https://docs.rs/rusty_ffmpeg/latest/rusty_ffmpeg/ffi/constant.AVPixelFormat_AV_PIX_FMT_NV12.html.

**Comment by Zerowalker** [comment]
oh noticed now i had messed up some re-exporting.
sorry for wasting your time!
