### ISSUE TITLE
Issue with ffmpeg 5 on Ubuntu 22.10

### ISSUE THREAD

**Issue by prateekmedia** [CCExtractor/rusty_ffmpeg#95]
Compiling ccextractor with rusty_ffmpeg and ffmpeg 5.0 on Ubuntu 22.10 gives this error, can you check if something is missing:

```
/usr/bin/ld: ./libccx_rust.a(rsmpeg-d3dd6e1fa3ffc9ea.rsmpeg.d0068580-cgu.10.rcgu.o): in function `<rsmpeg::avfilter::avfilter::AVFilterGraph as core::ops::drop::Drop>::drop':
/home/cfsmp3/.cargo/registry/src/github.com-1ecc6299db9ec823/rsmpeg-0.14.1+ffmpeg.6.0/src/avfilter/avfilter.rs:244: undefined reference to `avfilter_graph_free'
```

**Comment by ldm0** [comment]
`avfilter_graph_free` is a fairly basic symbol, and there is a FFmpeg 5.0 compatibility test in rsmpeg's CI([link](https://github.com/larksuite/rsmpeg/blob/589cd36f6a59a4eda0990e0621b6592bffe911f0/.github/workflows/ci.yml#L109)). I guess the ffmpeg build might be corrupted or something was missed. Any detailed error info?

**Comment by cfsmp3** [comment]
> `avfilter_graph_free` is a fairly basic symbol, and there is a FFmpeg 5.0 compatibility test in rsmpeg's CI([link](https://github.com/larksuite/rsmpeg/blob/589cd36f6a59a4eda0990e0621b6592bffe911f0/.github/workflows/ci.yml#L109)). I guess the ffmpeg build might be corrupted or something was missed. Any detailed error info?

See previous comment @ldm0 :-)

**Comment by ldm0** [comment]
Let me install a VirtualBox.

**Comment by ldm0** [comment]
@cfsmp3 @prateekmedia 
I reproduced this problem and found that `libavfilter` is missing on linking. After tweaking linker flag, the compilation succeed.
Here is the PR: https://github.com/CCExtractor/ccextractor/pull/1513
