### ISSUE TITLE
Support Multiple ffmpeg versions

### ISSUE THREAD

**Issue by prateekmedia** [CCExtractor/rusty_ffmpeg#96]
See Ubuntu 22.04 and before still have ffmpeg 4, but newer ubuntu have ffmpeg 5. Both of them are supported by ccextractor but if user needs to use ffmpeg5 then they have to add ffmpeg5 feature, but I think It would be better if we can support both ffmpeg4 and ffmpeg5 so it would work for both.

**Comment by ldm0** [comment]
`ffmpeg5` feature is for FFmpeg5-only features currently. You can remove the `ffmpeg5` feature to support both FFmpeg 4 and 5.

**Comment by prateekmedia** [comment]
Ok then
